# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
first_names = ["jim", "bob", "tom", "jill", "jane", "ann"]
last_names = ["smith", "white", "black", "nguyen", "kim"]
list_of_names = []


# create a list of random names and seed the model with them
10.times do |e| 
	list_of_names[e] = first_names[rand(first_names.size)] + " " + last_names[rand(last_names.size)]
end

list_of_names.each do |user|
	User.create(:name => user, :email => user +"@test.com", :username => user.gsub(/\s+/,""))
end

# Create a list of Petitions
petition_names = ["Property Taxes. Expanded Exemption for Disabled Veterans. Initiative Constitutional Amendment",
				  "Medical Marijuana. Patient Associations. Initiative Statute.",
				  "Government Spending Limits. Initiative Constitutional Amendment.",
				  "Prevents Issuance of Future High-Speed Rail Bonds. Initiative Statute.",
				  "Corporations. Eliminates State Constitutional Protections. Initiative Constitutional Amendment.",
				  "Education. Repeals Non-Discrimination Requirements for School Instruction. Narrows Requirement that Students Study Role and Contributions of Various Groups. Initiative Statute.",
				  "Tax on California Oil and Natural Gas. Revenues to Higher Education and General Fund. Initiative Statute.",
				  "Marijuana. Regulation and Taxation of Medical Use Industry. Reduced Criminal Penalties. Inititative Statute.",
				  "Tax to Fund Education, Preschools, and Child Care. Inititative Statute.",
				  "Political Contributions and Expenditures by Corporations. Shareholder Approval. Initiative Statute."]

petition_desc = ["Allows the Legislature to provide full or partial property tax exemption for a home belonging to a disabled veteran or the veteran's spouse, including an unmarried surviving spouse, if the veteran is receiving special monthly military disability compensation because of injury or disease incurred in military service, is blind in both eyes, has lost the use of two or more limbs, has brain syndrome, or died while on active duty. Exemption may not be combined with other real property exemptions. Summary of estimate by Legislative Analyst and Director of Finance of fiscal impact on state and local government: Potential minor reduction in property tax revenues for local governments as a result of increased property tax exemptions for certain veterans with severe service-related disabilities. Potential minor increase in state spending on K-12 schools and community colleges as a result of the small property tax decline.",
				 "Provides that patients qualified to use marijuana for medical purposes shall have the right to form an association for purposes of cultivating, processing and distributing medical marijuana within their association, and to recover reasonable costs incurred. Provides that neither the state nor any local government may prohibit operation of a medical marijuana patient association, including a storefront, unless a court finds it is an actual nuisance. Provides that medical marijuana patients have a property right to own and possess medical marijuana. Summary of estimate by Legislative Analyst and Director of Finance of fiscal impact on state and local government: Additional state and local tax revenues potentially in the low tens of millions of dollars annually from an increase in taxable sales of medical marijuana.",
				 "Resets state spending limit to fiscal year 2010-11 level. Requires state and local governments spend tax revenue exceeding limit to repay debt when debt is 5% or more of their spending limit. When state debt is less than 5% of state spending limit, splits excess revenue between schools and budget reserves or taxpayer refunds, depending on amount. When local government debt is less than 5% of applicable spending limit, returns excess revenue to taxpayers. Requires constitutional amendment to change terms. Forecloses Legislature's imposition, authorization, or submission to voters of tax increase absent two-thirds vote. Summary of estimate by Legislative Analyst and Director of Finance of fiscal impact on state and local government: For state government, a much greater likelihood that spending will be constrained by the constitutional spending limit. Consequently, state spending for ongoing programs' such as schools, community colleges, universities, health and social services, and corrections' may have to be reduced in certain years, potentially by billions of dollars. In addition, the measure could result in more state funding for reduction of bond debt, particularly in the near term, and in the future, more one-time funding for schools and community colleges, budget reserves, and taxpayer refunds.",
				 "Prevents the issuance and sale of the remaining amount of high-speed rail bonds previously approved by the voters to initiate construction of a high-speed train system. Allows the Legislature to redirect any unspent high-speed rail bond proceeds from high-speed rail purposes to repay those outstanding bonds. Summary of estimate by Legislative Analyst and Director of Finance of fiscal impact on state and local government: State debt-service savings of up to $709 million annually from not using state bond funds to support high-speed rail, depending on the actual reduction in bonds sold as a result of this measure. Unknown reduction in state and local revenues due to a somewhat lower level of economic activity in the state over the next several years, resulting from a loss of matching funds from the federal government or potential private investors.",
				 "Declares that corporations are not persons, thereby eliminating corporations' state constitutional protections. States that only human beings are valid and recognized people in California. Summary of estimate by Legislative Analyst and Director of Finance of fiscal impact on state and local government: Probably no significant fiscal effect on state or local government.",
				 "Repeals requirement that schools prohibit instructional materials that discriminate against persons based on their gender, religion, sexual orientation, disabilities, or other characteristics. Repeals requirements that school instructional materials recognize societal contributions of various groups to the economic, political, and social development of California and the United States. Prohibits exclusion of a historical figure from instructional materials solely on the basis that the historical figure is a member in, or possesses a characteristic associated with, a specified protected group. Summary of estimate by Legislative Analyst and Director of Finance of fiscal impact on state and local government: This measure would not impose additional costs on school districts.",
				 "Imposes 12.5 percent tax on value of oil and natural gas extracted in California. Allocates revenues one-third to higher education (half to California State University, half split between University of California and community colleges) and two-thirds to general fund. Provides new education funds shall augment, not count toward, existing education funding requirements. Dedicates 10 percent of new education funds to student grants. Requires California State University to use portion of funding for nursing programs. Prohibits passing tax on to consumers through higher fuel prices. Summary of estimate by Legislative Analyst and Director of Finance of fiscal impact on state and local government: Increased state revenues of about $3 billion per year initially, with two-thirds (about $2 billion) going to the state General Fund and one-third (about $1 billion) allocated to specific higher education purposes. Of the General Fund revenue increase, roughly half would likely go to higher funding for schools and community college districts, with the remainder available for any state purpose.",
				 "Establishes new government agency to regulate medical marijuana cultivation, manufacture, distribution, testing, and sale. Imposes agency fees, and 2.5% tax on medical marijuana retail sales. Allocates new revenues to agency administration, any remainder primarily to medical marijuana research and grants. Preempts local regulation of medical marijuana, except for zoning of medical marijuana dispensaries. Requires one dispensary per 50,000 residents unless limited or banned by local initiative. Bars state and local assistance to federal enforcement against medical marijuana. Reduces criminal penalties for marijuana possession, cultivation, transport, or sale. Summary of estimate by Legislative Analyst and Director of Finance of fiscal impact on state and local government: Savings potentially up to several tens of millions of dollars annually to state and local governments from reductions in various criminal justice costs related to enforcing marijuana crimes. Additional state tax revenues in the low tens of millions of dollars annually from a new supplemental tax on medical marijuana sales, used for various regulatory, research, education, and health care purposes generally related to medical marijuana. Increased costs to regulate medical marijuana potentially in the tens of millions of dollars annually, offset by fees and/or taxes authorized by the measure.",
				 "Increases personal income tax rates for annual earnings over $7,316 with a sliding scale that increases the tax rate from .4% for lowest individual earners to 2.2% for individuals earning over $2.5 million. Tax increase ends after twelve years. Allocates new revenues 85% to K-12 schools and 15% to preschools and child care. Provides K-12 funds on school-specific, per-pupil basis, subject to local control. Requires local education budgeting to be school-specific. Requires oversight, audits, and public input. Prohibits state from directing or using new funds. Summary of estimate by Legislative Analyst and Director of Finance of fiscal impact on state and local government: Increased state personal income tax revenues beginning in 2013 and ending in 2024. Estimates of the revenue increases vary from $10 billion to $11 billion per year initially, tending to increase over time. The revenues would be dedicated to K-12 education (85 percent of the funds) and early care and education programs (15 percent) and would supplement existing funding for these programs. In years with stronger growth in state personal income tax revenues, some of the revenues raised by this measure' several hundred million dollars per year' would be used to pay education debt service costs, resulting in state savings.",
				 "Prohibits corporations and other business entities from making contributions or expenditures for political activities without shareholders' prior informed approval. Reduces the total amount of any contribution or expenditure approved by the percentage of shares not voted for approval. Defines political activities to include those related to candidates, ballot measures, issue advocacy, political parties, committees, voter registration, or any other political or legislative causes. Imposes criminal penalties for violations against persons spending, consenting to, or receiving prohibited contributions or expenditures. Requires detailed reporting to shareholders. Summary of estimate by Legislative Analyst and Director of Finance of fiscal impact on state and local government: Increased annual state enforcement costs of potentially several hundred thousand dollars, partially offset by increased fine revenues."]

10.times do |e|
	Petition.create(:name => petition_names[e], :description => petition_desc[e])
end